server:
  port: 4111
spring:
  application:
    name: policy-email-service
  datasource:
    url: jdbc:mysql://localhost:3306/emailsdb
    username: root
    password: subhanAllah123@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
    instances:
      createEmailCircuitBreaker:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 3
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2